// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: dsl.proto

package dslv1

import (
	v1 "ebusta/api/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawInput) Reset() {
	*x = RawInput{}
	mi := &file_dsl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInput) ProtoMessage() {}

func (x *RawInput) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInput.ProtoReflect.Descriptor instead.
func (*RawInput) Descriptor() ([]byte, []int) {
	return file_dsl_proto_rawDescGZIP(), []int{0}
}

func (x *RawInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SQuery struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Data      string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IsSuccess bool                   `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	ErrorMsg  string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// Добавляем AST дерево
	Ast           *v1.SearchQuery `protobuf:"bytes,4,opt,name=ast,proto3" json:"ast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQuery) Reset() {
	*x = SQuery{}
	mi := &file_dsl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQuery) ProtoMessage() {}

func (x *SQuery) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQuery.ProtoReflect.Descriptor instead.
func (*SQuery) Descriptor() ([]byte, []int) {
	return file_dsl_proto_rawDescGZIP(), []int{1}
}

func (x *SQuery) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SQuery) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *SQuery) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SQuery) GetAst() *v1.SearchQuery {
	if x != nil {
		return x.Ast
	}
	return nil
}

var File_dsl_proto protoreflect.FileDescriptor

const file_dsl_proto_rawDesc = "" +
	"\n" +
	"\tdsl.proto\x12\rebusta.dsl.v1\x1a\fcommon.proto\" \n" +
	"\bRawInput\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x8a\x01\n" +
	"\x06SQuery\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"is_success\x18\x02 \x01(\bR\tisSuccess\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x120\n" +
	"\x03ast\x18\x04 \x01(\v2\x1e.ebusta.library.v1.SearchQueryR\x03ast2O\n" +
	"\x0eDslTransformer\x12=\n" +
	"\tTransform\x12\x17.ebusta.dsl.v1.RawInput\x1a\x15.ebusta.dsl.v1.SQuery\"\x00B\x19Z\x17ebusta/api/dsl/v1;dslv1b\x06proto3"

var (
	file_dsl_proto_rawDescOnce sync.Once
	file_dsl_proto_rawDescData []byte
)

func file_dsl_proto_rawDescGZIP() []byte {
	file_dsl_proto_rawDescOnce.Do(func() {
		file_dsl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dsl_proto_rawDesc), len(file_dsl_proto_rawDesc)))
	})
	return file_dsl_proto_rawDescData
}

var file_dsl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dsl_proto_goTypes = []any{
	(*RawInput)(nil),       // 0: ebusta.dsl.v1.RawInput
	(*SQuery)(nil),         // 1: ebusta.dsl.v1.SQuery
	(*v1.SearchQuery)(nil), // 2: ebusta.library.v1.SearchQuery
}
var file_dsl_proto_depIdxs = []int32{
	2, // 0: ebusta.dsl.v1.SQuery.ast:type_name -> ebusta.library.v1.SearchQuery
	0, // 1: ebusta.dsl.v1.DslTransformer.Transform:input_type -> ebusta.dsl.v1.RawInput
	1, // 2: ebusta.dsl.v1.DslTransformer.Transform:output_type -> ebusta.dsl.v1.SQuery
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dsl_proto_init() }
func file_dsl_proto_init() {
	if File_dsl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dsl_proto_rawDesc), len(file_dsl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dsl_proto_goTypes,
		DependencyIndexes: file_dsl_proto_depIdxs,
		MessageInfos:      file_dsl_proto_msgTypes,
	}.Build()
	File_dsl_proto = out.File
	file_dsl_proto_goTypes = nil
	file_dsl_proto_depIdxs = nil
}
