// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: dsl.proto

package dslv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DslTransformer_Transform_FullMethodName = "/ebusta.dsl.v1.DslTransformer/Transform"
)

// DslTransformerClient is the client API for DslTransformer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DslTransformerClient interface {
	Transform(ctx context.Context, in *RawInput, opts ...grpc.CallOption) (*SQuery, error)
}

type dslTransformerClient struct {
	cc grpc.ClientConnInterface
}

func NewDslTransformerClient(cc grpc.ClientConnInterface) DslTransformerClient {
	return &dslTransformerClient{cc}
}

func (c *dslTransformerClient) Transform(ctx context.Context, in *RawInput, opts ...grpc.CallOption) (*SQuery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SQuery)
	err := c.cc.Invoke(ctx, DslTransformer_Transform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DslTransformerServer is the server API for DslTransformer service.
// All implementations must embed UnimplementedDslTransformerServer
// for forward compatibility.
type DslTransformerServer interface {
	Transform(context.Context, *RawInput) (*SQuery, error)
	mustEmbedUnimplementedDslTransformerServer()
}

// UnimplementedDslTransformerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDslTransformerServer struct{}

func (UnimplementedDslTransformerServer) Transform(context.Context, *RawInput) (*SQuery, error) {
	return nil, status.Error(codes.Unimplemented, "method Transform not implemented")
}
func (UnimplementedDslTransformerServer) mustEmbedUnimplementedDslTransformerServer() {}
func (UnimplementedDslTransformerServer) testEmbeddedByValue()                        {}

// UnsafeDslTransformerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DslTransformerServer will
// result in compilation errors.
type UnsafeDslTransformerServer interface {
	mustEmbedUnimplementedDslTransformerServer()
}

func RegisterDslTransformerServer(s grpc.ServiceRegistrar, srv DslTransformerServer) {
	// If the following call panics, it indicates UnimplementedDslTransformerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DslTransformer_ServiceDesc, srv)
}

func _DslTransformer_Transform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DslTransformerServer).Transform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DslTransformer_Transform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DslTransformerServer).Transform(ctx, req.(*RawInput))
	}
	return interceptor(ctx, in, info, handler)
}

// DslTransformer_ServiceDesc is the grpc.ServiceDesc for DslTransformer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DslTransformer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ebusta.dsl.v1.DslTransformer",
	HandlerType: (*DslTransformerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transform",
			Handler:    _DslTransformer_Transform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dsl.proto",
}
