// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: query_builder.proto

package qbv1

import (
	v1 "ebusta/api/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_DSL      QueryType = 0 // Сложный JSON запрос (endpoint /_search)
	QueryType_TEMPLATE QueryType = 1 // Вызов шаблона (endpoint /_search/template)
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "DSL",
		1: "TEMPLATE",
	}
	QueryType_value = map[string]int32{
		"DSL":      0,
		"TEMPLATE": 1,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_query_builder_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_query_builder_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_query_builder_proto_rawDescGZIP(), []int{0}
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ast           *v1.SearchQuery        `protobuf:"bytes,1,opt,name=ast,proto3" json:"ast,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	From          int32                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_query_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_query_builder_proto_rawDescGZIP(), []int{0}
}

func (x *BuildRequest) GetAst() *v1.SearchQuery {
	if x != nil {
		return x.Ast
	}
	return nil
}

func (x *BuildRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BuildRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BodyJson      string                 `protobuf:"bytes,1,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`      // JSON тела запроса
	Type          QueryType              `protobuf:"varint,2,opt,name=type,proto3,enum=ebusta.qb.v1.QueryType" json:"type,omitempty"` // Подсказка, куда слать запрос
	IsSuccess     bool                   `protobuf:"varint,3,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_query_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_query_builder_proto_rawDescGZIP(), []int{1}
}

func (x *BuildResponse) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *BuildResponse) GetType() QueryType {
	if x != nil {
		return x.Type
	}
	return QueryType_DSL
}

func (x *BuildResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *BuildResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_query_builder_proto protoreflect.FileDescriptor

const file_query_builder_proto_rawDesc = "" +
	"\n" +
	"\x13query_builder.proto\x12\febusta.qb.v1\x1a\fcommon.proto\"h\n" +
	"\fBuildRequest\x120\n" +
	"\x03ast\x18\x01 \x01(\v2\x1e.ebusta.library.v1.SearchQueryR\x03ast\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x05R\x04from\"\x95\x01\n" +
	"\rBuildResponse\x12\x1b\n" +
	"\tbody_json\x18\x01 \x01(\tR\bbodyJson\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.ebusta.qb.v1.QueryTypeR\x04type\x12\x1d\n" +
	"\n" +
	"is_success\x18\x03 \x01(\bR\tisSuccess\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg*\"\n" +
	"\tQueryType\x12\a\n" +
	"\x03DSL\x10\x00\x12\f\n" +
	"\bTEMPLATE\x10\x012R\n" +
	"\fQueryBuilder\x12B\n" +
	"\x05Build\x12\x1a.ebusta.qb.v1.BuildRequest\x1a\x1b.ebusta.qb.v1.BuildResponse\"\x00B\x17Z\x15ebusta/api/qb/v1;qbv1b\x06proto3"

var (
	file_query_builder_proto_rawDescOnce sync.Once
	file_query_builder_proto_rawDescData []byte
)

func file_query_builder_proto_rawDescGZIP() []byte {
	file_query_builder_proto_rawDescOnce.Do(func() {
		file_query_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_builder_proto_rawDesc), len(file_query_builder_proto_rawDesc)))
	})
	return file_query_builder_proto_rawDescData
}

var file_query_builder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_query_builder_proto_goTypes = []any{
	(QueryType)(0),         // 0: ebusta.qb.v1.QueryType
	(*BuildRequest)(nil),   // 1: ebusta.qb.v1.BuildRequest
	(*BuildResponse)(nil),  // 2: ebusta.qb.v1.BuildResponse
	(*v1.SearchQuery)(nil), // 3: ebusta.library.v1.SearchQuery
}
var file_query_builder_proto_depIdxs = []int32{
	3, // 0: ebusta.qb.v1.BuildRequest.ast:type_name -> ebusta.library.v1.SearchQuery
	0, // 1: ebusta.qb.v1.BuildResponse.type:type_name -> ebusta.qb.v1.QueryType
	1, // 2: ebusta.qb.v1.QueryBuilder.Build:input_type -> ebusta.qb.v1.BuildRequest
	2, // 3: ebusta.qb.v1.QueryBuilder.Build:output_type -> ebusta.qb.v1.BuildResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_builder_proto_init() }
func file_query_builder_proto_init() {
	if File_query_builder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_builder_proto_rawDesc), len(file_query_builder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_builder_proto_goTypes,
		DependencyIndexes: file_query_builder_proto_depIdxs,
		EnumInfos:         file_query_builder_proto_enumTypes,
		MessageInfos:      file_query_builder_proto_msgTypes,
	}.Build()
	File_query_builder_proto = out.File
	file_query_builder_proto_goTypes = nil
	file_query_builder_proto_depIdxs = nil
}
