// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: query_builder.proto

package qbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryBuilder_Build_FullMethodName = "/ebusta.qb.v1.QueryBuilder/Build"
)

// QueryBuilderClient is the client API for QueryBuilder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryBuilderClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type queryBuilderClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryBuilderClient(cc grpc.ClientConnInterface) QueryBuilderClient {
	return &queryBuilderClient{cc}
}

func (c *queryBuilderClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, QueryBuilder_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryBuilderServer is the server API for QueryBuilder service.
// All implementations must embed UnimplementedQueryBuilderServer
// for forward compatibility.
type QueryBuilderServer interface {
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	mustEmbedUnimplementedQueryBuilderServer()
}

// UnimplementedQueryBuilderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryBuilderServer struct{}

func (UnimplementedQueryBuilderServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedQueryBuilderServer) mustEmbedUnimplementedQueryBuilderServer() {}
func (UnimplementedQueryBuilderServer) testEmbeddedByValue()                      {}

// UnsafeQueryBuilderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryBuilderServer will
// result in compilation errors.
type UnsafeQueryBuilderServer interface {
	mustEmbedUnimplementedQueryBuilderServer()
}

func RegisterQueryBuilderServer(s grpc.ServiceRegistrar, srv QueryBuilderServer) {
	// If the following call panics, it indicates UnimplementedQueryBuilderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryBuilder_ServiceDesc, srv)
}

func _QueryBuilder_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryBuilderServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryBuilder_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryBuilderServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryBuilder_ServiceDesc is the grpc.ServiceDesc for QueryBuilder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryBuilder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ebusta.qb.v1.QueryBuilder",
	HandlerType: (*QueryBuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _QueryBuilder_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query_builder.proto",
}
