// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: library.proto

package libraryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogicalOp int32

const (
	LogicalOp_AND LogicalOp = 0
	LogicalOp_OR  LogicalOp = 1
)

// Enum value maps for LogicalOp.
var (
	LogicalOp_name = map[int32]string{
		0: "AND",
		1: "OR",
	}
	LogicalOp_value = map[string]int32{
		"AND": 0,
		"OR":  1,
	}
)

func (x LogicalOp) Enum() *LogicalOp {
	p := new(LogicalOp)
	*p = x
	return p
}

func (x LogicalOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalOp) Descriptor() protoreflect.EnumDescriptor {
	return file_library_proto_enumTypes[0].Descriptor()
}

func (LogicalOp) Type() protoreflect.EnumType {
	return &file_library_proto_enumTypes[0]
}

func (x LogicalOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalOp.Descriptor instead.
func (LogicalOp) EnumDescriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{0}
}

type Operator int32

const (
	Operator_OP_EQUALS   Operator = 0
	Operator_OP_CONTAINS Operator = 1
	Operator_OP_REGEX    Operator = 2
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "OP_EQUALS",
		1: "OP_CONTAINS",
		2: "OP_REGEX",
	}
	Operator_value = map[string]int32{
		"OP_EQUALS":   0,
		"OP_CONTAINS": 1,
		"OP_REGEX":    2,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_library_proto_enumTypes[1].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_library_proto_enumTypes[1]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{1}
}

type RawInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawInput) Reset() {
	*x = RawInput{}
	mi := &file_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInput) ProtoMessage() {}

func (x *RawInput) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInput.ProtoReflect.Descriptor instead.
func (*RawInput) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{0}
}

func (x *RawInput) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type UnmarshaledMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *SearchQuery           `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Meta          *MessageMeta           `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmarshaledMessage) Reset() {
	*x = UnmarshaledMessage{}
	mi := &file_library_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmarshaledMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarshaledMessage) ProtoMessage() {}

func (x *UnmarshaledMessage) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarshaledMessage.ProtoReflect.Descriptor instead.
func (*UnmarshaledMessage) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{1}
}

func (x *UnmarshaledMessage) GetQuery() *SearchQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *UnmarshaledMessage) GetMeta() *MessageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type MessageMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	CanonicalForm string                 `protobuf:"bytes,2,opt,name=canonical_form,json=canonicalForm,proto3" json:"canonical_form,omitempty"`
	AstPlan       *SearchQuery           `protobuf:"bytes,3,opt,name=ast_plan,json=astPlan,proto3" json:"ast_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMeta) Reset() {
	*x = MessageMeta{}
	mi := &file_library_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMeta) ProtoMessage() {}

func (x *MessageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMeta.ProtoReflect.Descriptor instead.
func (*MessageMeta) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{2}
}

func (x *MessageMeta) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MessageMeta) GetCanonicalForm() string {
	if x != nil {
		return x.CanonicalForm
	}
	return ""
}

func (x *MessageMeta) GetAstPlan() *SearchQuery {
	if x != nil {
		return x.AstPlan
	}
	return nil
}

type SearchQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Node:
	//
	//	*SearchQuery_Filter
	//	*SearchQuery_Logical
	//	*SearchQuery_Negation
	Node          isSearchQuery_Node `protobuf_oneof:"node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	mi := &file_library_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{3}
}

func (x *SearchQuery) GetNode() isSearchQuery_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *SearchQuery) GetFilter() *FilterNode {
	if x != nil {
		if x, ok := x.Node.(*SearchQuery_Filter); ok {
			return x.Filter
		}
	}
	return nil
}

func (x *SearchQuery) GetLogical() *LogicalNode {
	if x != nil {
		if x, ok := x.Node.(*SearchQuery_Logical); ok {
			return x.Logical
		}
	}
	return nil
}

func (x *SearchQuery) GetNegation() *NotNode {
	if x != nil {
		if x, ok := x.Node.(*SearchQuery_Negation); ok {
			return x.Negation
		}
	}
	return nil
}

type isSearchQuery_Node interface {
	isSearchQuery_Node()
}

type SearchQuery_Filter struct {
	Filter *FilterNode `protobuf:"bytes,1,opt,name=filter,proto3,oneof"`
}

type SearchQuery_Logical struct {
	Logical *LogicalNode `protobuf:"bytes,2,opt,name=logical,proto3,oneof"`
}

type SearchQuery_Negation struct {
	Negation *NotNode `protobuf:"bytes,3,opt,name=negation,proto3,oneof"`
}

func (*SearchQuery_Filter) isSearchQuery_Node() {}

func (*SearchQuery_Logical) isSearchQuery_Node() {}

func (*SearchQuery_Negation) isSearchQuery_Node() {}

type FilterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Operator      Operator               `protobuf:"varint,3,opt,name=operator,proto3,enum=libraryv1.Operator" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNode) Reset() {
	*x = FilterNode{}
	mi := &file_library_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNode) ProtoMessage() {}

func (x *FilterNode) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNode.ProtoReflect.Descriptor instead.
func (*FilterNode) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{4}
}

func (x *FilterNode) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FilterNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FilterNode) GetOperator() Operator {
	if x != nil {
		return x.Operator
	}
	return Operator_OP_EQUALS
}

type LogicalNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            LogicalOp              `protobuf:"varint,1,opt,name=op,proto3,enum=libraryv1.LogicalOp" json:"op,omitempty"`
	Nodes         []*SearchQuery         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalNode) Reset() {
	*x = LogicalNode{}
	mi := &file_library_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalNode) ProtoMessage() {}

func (x *LogicalNode) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalNode.ProtoReflect.Descriptor instead.
func (*LogicalNode) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{5}
}

func (x *LogicalNode) GetOp() LogicalOp {
	if x != nil {
		return x.Op
	}
	return LogicalOp_AND
}

func (x *LogicalNode) GetNodes() []*SearchQuery {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NotNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *SearchQuery           `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotNode) Reset() {
	*x = NotNode{}
	mi := &file_library_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotNode) ProtoMessage() {}

func (x *NotNode) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotNode.ProtoReflect.Descriptor instead.
func (*NotNode) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{6}
}

func (x *NotNode) GetNode() *SearchQuery {
	if x != nil {
		return x.Node
	}
	return nil
}

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *SearchQuery           `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_library_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{7}
}

func (x *DataRequest) GetQuery() *SearchQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Books         []*Book                `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_library_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{8}
}

func (x *DataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DataResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Books         []*Book                `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_library_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Response) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *Response) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CanonicalForm string                 `protobuf:"bytes,2,opt,name=canonical_form,json=canonicalForm,proto3" json:"canonical_form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	mi := &file_library_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseMeta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ResponseMeta) GetCanonicalForm() string {
	if x != nil {
		return x.CanonicalForm
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawInput      string                 `protobuf:"bytes,1,opt,name=raw_input,json=rawInput,proto3" json:"raw_input,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_library_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteRequest) GetRawInput() string {
	if x != nil {
		return x.RawInput
	}
	return ""
}

func (x *ExecuteRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Authors       []string               `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_library_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{12}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

var File_library_proto protoreflect.FileDescriptor

const file_library_proto_rawDesc = "" +
	"\n" +
	"\rlibrary.proto\x12\tlibraryv1\"\x1e\n" +
	"\bRawInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"n\n" +
	"\x12UnmarshaledMessage\x12,\n" +
	"\x05query\x18\x01 \x01(\v2\x16.libraryv1.SearchQueryR\x05query\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.libraryv1.MessageMetaR\x04meta\"\x7f\n" +
	"\vMessageMeta\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12%\n" +
	"\x0ecanonical_form\x18\x02 \x01(\tR\rcanonicalForm\x121\n" +
	"\bast_plan\x18\x03 \x01(\v2\x16.libraryv1.SearchQueryR\aastPlan\"\xac\x01\n" +
	"\vSearchQuery\x12/\n" +
	"\x06filter\x18\x01 \x01(\v2\x15.libraryv1.FilterNodeH\x00R\x06filter\x122\n" +
	"\alogical\x18\x02 \x01(\v2\x16.libraryv1.LogicalNodeH\x00R\alogical\x120\n" +
	"\bnegation\x18\x03 \x01(\v2\x12.libraryv1.NotNodeH\x00R\bnegationB\x06\n" +
	"\x04node\"i\n" +
	"\n" +
	"FilterNode\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12/\n" +
	"\boperator\x18\x03 \x01(\x0e2\x13.libraryv1.OperatorR\boperator\"a\n" +
	"\vLogicalNode\x12$\n" +
	"\x02op\x18\x01 \x01(\x0e2\x14.libraryv1.LogicalOpR\x02op\x12,\n" +
	"\x05nodes\x18\x02 \x03(\v2\x16.libraryv1.SearchQueryR\x05nodes\"5\n" +
	"\aNotNode\x12*\n" +
	"\x04node\x18\x01 \x01(\v2\x16.libraryv1.SearchQueryR\x04node\";\n" +
	"\vDataRequest\x12,\n" +
	"\x05query\x18\x01 \x01(\v2\x16.libraryv1.SearchQueryR\x05query\"M\n" +
	"\fDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x05books\x18\x02 \x03(\v2\x0f.libraryv1.BookR\x05books\"v\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x05books\x18\x02 \x03(\v2\x0f.libraryv1.BookR\x05books\x12+\n" +
	"\x04meta\x18\x03 \x01(\v2\x17.libraryv1.ResponseMetaR\x04meta\"P\n" +
	"\fResponseMeta\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12%\n" +
	"\x0ecanonical_form\x18\x02 \x01(\tR\rcanonicalForm\"H\n" +
	"\x0eExecuteRequest\x12\x1b\n" +
	"\traw_input\x18\x01 \x01(\tR\brawInput\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"F\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aauthors\x18\x03 \x03(\tR\aauthors*\x1c\n" +
	"\tLogicalOp\x12\a\n" +
	"\x03AND\x10\x00\x12\x06\n" +
	"\x02OR\x10\x01*8\n" +
	"\bOperator\x12\r\n" +
	"\tOP_EQUALS\x10\x00\x12\x0f\n" +
	"\vOP_CONTAINS\x10\x01\x12\f\n" +
	"\bOP_REGEX\x10\x022I\n" +
	"\vDataService\x12:\n" +
	"\aGetData\x12\x16.libraryv1.DataRequest\x1a\x17.libraryv1.DataResponse2X\n" +
	"\x17MessageConverterService\x12=\n" +
	"\aConvert\x12\x13.libraryv1.RawInput\x1a\x1d.libraryv1.UnmarshaledMessage2W\n" +
	"\x10ProcessorService\x12C\n" +
	"\rHandleCommand\x12\x1d.libraryv1.UnmarshaledMessage\x1a\x13.libraryv1.Response2I\n" +
	"\fOrchestrator\x129\n" +
	"\aExecute\x12\x19.libraryv1.ExecuteRequest\x1a\x13.libraryv1.ResponseB\x1fZ\x1debusta/api/proto/v1;libraryv1b\x06proto3"

var (
	file_library_proto_rawDescOnce sync.Once
	file_library_proto_rawDescData []byte
)

func file_library_proto_rawDescGZIP() []byte {
	file_library_proto_rawDescOnce.Do(func() {
		file_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_library_proto_rawDesc), len(file_library_proto_rawDesc)))
	})
	return file_library_proto_rawDescData
}

var file_library_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_library_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_library_proto_goTypes = []any{
	(LogicalOp)(0),             // 0: libraryv1.LogicalOp
	(Operator)(0),              // 1: libraryv1.Operator
	(*RawInput)(nil),           // 2: libraryv1.RawInput
	(*UnmarshaledMessage)(nil), // 3: libraryv1.UnmarshaledMessage
	(*MessageMeta)(nil),        // 4: libraryv1.MessageMeta
	(*SearchQuery)(nil),        // 5: libraryv1.SearchQuery
	(*FilterNode)(nil),         // 6: libraryv1.FilterNode
	(*LogicalNode)(nil),        // 7: libraryv1.LogicalNode
	(*NotNode)(nil),            // 8: libraryv1.NotNode
	(*DataRequest)(nil),        // 9: libraryv1.DataRequest
	(*DataResponse)(nil),       // 10: libraryv1.DataResponse
	(*Response)(nil),           // 11: libraryv1.Response
	(*ResponseMeta)(nil),       // 12: libraryv1.ResponseMeta
	(*ExecuteRequest)(nil),     // 13: libraryv1.ExecuteRequest
	(*Book)(nil),               // 14: libraryv1.Book
}
var file_library_proto_depIdxs = []int32{
	5,  // 0: libraryv1.UnmarshaledMessage.query:type_name -> libraryv1.SearchQuery
	4,  // 1: libraryv1.UnmarshaledMessage.meta:type_name -> libraryv1.MessageMeta
	5,  // 2: libraryv1.MessageMeta.ast_plan:type_name -> libraryv1.SearchQuery
	6,  // 3: libraryv1.SearchQuery.filter:type_name -> libraryv1.FilterNode
	7,  // 4: libraryv1.SearchQuery.logical:type_name -> libraryv1.LogicalNode
	8,  // 5: libraryv1.SearchQuery.negation:type_name -> libraryv1.NotNode
	1,  // 6: libraryv1.FilterNode.operator:type_name -> libraryv1.Operator
	0,  // 7: libraryv1.LogicalNode.op:type_name -> libraryv1.LogicalOp
	5,  // 8: libraryv1.LogicalNode.nodes:type_name -> libraryv1.SearchQuery
	5,  // 9: libraryv1.NotNode.node:type_name -> libraryv1.SearchQuery
	5,  // 10: libraryv1.DataRequest.query:type_name -> libraryv1.SearchQuery
	14, // 11: libraryv1.DataResponse.books:type_name -> libraryv1.Book
	14, // 12: libraryv1.Response.books:type_name -> libraryv1.Book
	12, // 13: libraryv1.Response.meta:type_name -> libraryv1.ResponseMeta
	9,  // 14: libraryv1.DataService.GetData:input_type -> libraryv1.DataRequest
	2,  // 15: libraryv1.MessageConverterService.Convert:input_type -> libraryv1.RawInput
	3,  // 16: libraryv1.ProcessorService.HandleCommand:input_type -> libraryv1.UnmarshaledMessage
	13, // 17: libraryv1.Orchestrator.Execute:input_type -> libraryv1.ExecuteRequest
	10, // 18: libraryv1.DataService.GetData:output_type -> libraryv1.DataResponse
	3,  // 19: libraryv1.MessageConverterService.Convert:output_type -> libraryv1.UnmarshaledMessage
	11, // 20: libraryv1.ProcessorService.HandleCommand:output_type -> libraryv1.Response
	11, // 21: libraryv1.Orchestrator.Execute:output_type -> libraryv1.Response
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_library_proto_init() }
func file_library_proto_init() {
	if File_library_proto != nil {
		return
	}
	file_library_proto_msgTypes[3].OneofWrappers = []any{
		(*SearchQuery_Filter)(nil),
		(*SearchQuery_Logical)(nil),
		(*SearchQuery_Negation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_library_proto_rawDesc), len(file_library_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_library_proto_goTypes,
		DependencyIndexes: file_library_proto_depIdxs,
		EnumInfos:         file_library_proto_enumTypes,
		MessageInfos:      file_library_proto_msgTypes,
	}.Build()
	File_library_proto = out.File
	file_library_proto_goTypes = nil
	file_library_proto_depIdxs = nil
}
