;;; search.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))
  (sb-ext:muffle-conditions sb-kernel:redefinition-with-defun)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.EBUSTA.LIBRARY.V1")
    (cl:defpackage "CL-PROTOBUFS.EBUSTA.LIBRARY.V1" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.EBUSTA.LIBRARY.V1-RPC")
    (cl:defpackage "CL-PROTOBUFS.EBUSTA.LIBRARY.V1-RPC" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.EBUSTA.LIBRARY.V1")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'search
    :syntax :proto3

    :package "ebusta.library.v1")
)


;;; Top-Level messages

(pi:define-message convert-request
    ()
  ;; Fields
  (raw-query
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "rawQuery"))

(pi:define-message filter-node
    ()
  ;; Fields
  (field
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "field")
  (value
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "value")
  (operator
   :index 3 :type cl-protobufs:int32 :kind :scalar :label (:optional) :field-presence :implicit :json-name "operator"))

(pi:define-message logical-node
    ()
  ;; Fields
  (op
   :index 1 :type cl-protobufs:int32 :kind :scalar :label (:optional) :field-presence :implicit :json-name "op")
  (nodes
   :index 2 :type search-query :kind :message :label (:repeated :list) :field-presence :implicit :json-name "nodes"))

(pi:define-message search-query
    ()
  ;; Fields
  (pi:define-oneof query ()
    (filter
     :index 1 :type filter-node :kind :message :label (:optional) :field-presence :explicit :json-name "filter")
    (logical
     :index 2 :type logical-node :kind :message :label (:optional) :field-presence :explicit :json-name "logical")))

;;; Services
(pi:define-service message-converter
    (:source-location #P"search.proto")
  (convert (
    convert-request =>
    search-query)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"search.proto" 'search)
)

(cl:export '(convert-request
field
filter
filter-node
logical
logical-node
message-converter
nodes
op
operator
raw-query
search
search-query
value))

(cl:in-package "CL-PROTOBUFS.EBUSTA.LIBRARY.V1-RPC")

(cl:export '(call-convert
convert))
