FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl netcat-openbsd && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /app /var/log/ebusta

WORKDIR /app

COPY ./bin/datamanager /app/datamanager
COPY ./deploy/ebusta.docker.yaml /app/ebusta.yaml

EXPOSE 50051

ENTRYPOINT ["/app/datamanager"]
