FROM debian:stable-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./bin/telegram-bot /app/telegram-bot
COPY ./ebusta.yaml /app/ebusta.yaml

ENTRYPOINT ["/app/telegram-bot"]
