FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl netcat-openbsd && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /app /var/log/ebusta /data

WORKDIR /app

COPY ./bin/plasma-node /app/plasma-node
COPY ./deploy/ebusta.docker.yaml /app/ebusta.yaml

EXPOSE 50112

ENTRYPOINT ["/app/plasma-node"]
