FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /app /var/log/ebusta

WORKDIR /app

COPY ./bin/web-frontend /app/web-frontend
COPY ./deploy/ebusta.docker.yaml /app/ebusta.yaml

EXPOSE 3000

ENTRYPOINT ["/app/web-frontend"]
