FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /app /var/log/ebusta

WORKDIR /app

COPY ./bin/gateway /app/gateway
COPY ./ebusta.yaml /app/ebusta.yaml

EXPOSE 8443

ENTRYPOINT ["/app/gateway"]
