all:
  children:
    public:
      hosts:
        yuro:
          ansible_host: 192.168.1.179
    internal:
      hosts:
        yuro:
          ansible_host: 192.168.1.179
        neptune:
          ansible_host: 192.168.1.140
    bulker:
      hosts:
        cloud-1:
          ansible_host: 141.105.64.173
          ansible_user: serge
          f2bulker_install_dir: /opt/f2bulker
          opensearch_url: http://localhost:9200
